[package]
name = "todolist"
version = "1.0.0"
authors = []

[addresses]
todolist_addr='c6c07218d79a806380ca67761905063ec7a78d41f79619f4562462a0f8b6be11'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
